package com.jinke.mindmap;

public enum OutLineStyle {
	STRAIGHT_STROKE_HALF_BOX,
	STRAIGHT_STROKE_HALF_BOX_LEFT ,
	STRAIGHT_STROKE_HALF_BOX_RIGHT ,
	STRAIGHT_STROKE_HALF_BOX_LEFT_AND_RIGHT ,
	
	STRAIGHT_STROKE_BOX,
	STRAIGHT_FILL_BOX,
	STRAIGHT_STROKE_AND_FILL_BOX,
	
	OVAL_STROKE_HALF_BOX,
	OVAL_STROKE_HALF_BOX_LEFT ,
	OVAL_STROKE_HALF_BOX_RIGHT ,
	OVAL_STROKE_HALF_BOX_LEFT_AND_RIGHT ,
	
	OVAL_STROKE_BOX,
	OVAL_FILL_BOX,
	OVAL_STROKE_AND_FILL_BOX
}
